### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by captaincoffee** [captaincoffee/p218#22]
I have the current site up on Netlify. Still needs work.
The site is fast!!
Much faster than Facebook, Amazon, etc.
Even using the phone system is great!

Can the Bootstrap css and js be trimmed of unused parts?
Does Netlify concatenate and minify the css and js on build? (I think I read that they do, but can't find it)

[Thoughts: I only changed about 12 items in BS _variables, and the custom css would be needed in any event. Would using a CDN for BS make things more simple? Does BS carry over from one site to the other?]

**Comment by djacquel** [comment]
Jekyll + Netlify CDNs + simplicity = Yes we are fast !
Our current transfert for css is 30kb and js 50kb. No need to optimize yet. 
Everything is gziped by the servers.
On the other side, algolia sends 130kb of js+datas for search but it's not a problem.
Our main concern will be accessibility and  SEO.
Resources optimization will come latter.

**Comment by captaincoffee** [comment]
Great!
I thought they were much larger.
