### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by captaincoffee** [captaincoffee/p218#8]
P2 logos, favicons, and similar should be ready in the next 7-10 days.

**Comment by captaincoffee** [comment]
Items are here:
https://github.com/captaincoffee/p2/tree/master/icons_and_logos

**Comment by djacquel** [comment]
Imported

**Comment by djacquel** [comment]
I still have to link all this in documents head.
So reopen !

**Comment by djacquel** [comment]
ios, android, safari and ie/edge icons are online

**Comment by captaincoffee** [comment]
This needs to be the P2 icons.

**Comment by djacquel** [comment]
P2 not iP
