### ISSUE TITLE
Investigate use of jekyll/paginationV2 for KB tags and categories pagination

### ISSUE THREAD

**Issue by djacquel** [captaincoffee/p218#9]
[jekyll/paginationV2 repo](https://github.com/sverrirs/jekyll-paginate-v2)

After some deep inspection in paginate v2 code and behavior, it seems to be what we need for kb.

Pros : 
 - this does tags and categories indexes creation and pagination out of the box

Cons :
 - **edit: this is [managed by a plugin](https://github.com/captaincoffee/p218/blob/master/_plugins/hook-collection-category-from-path.rb) that removes index.html** generated page urls have "index.html" appended. They have hard coded it [here](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/lib/jekyll-paginate-v2/autopages/pages/baseAutoPage.rb#L8) and [here](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/lib/jekyll-paginate-v2/autopages/pages/baseAutoPage.rb#L40). An [issue is open](https://github.com/sverrirs/jekyll-paginate-v2/issues/98) on this topic, I will certainly contribute on this.
 - it is resources consuming when generating posts, categories and tags index and pagination.

I still have some questions/work before I close this issue.

- Will we use tag cloud ? This can be a huge cloud.
- I we use this plugin, I don't need to use mine for kb categories page generation. I will need to refactor menu bar for KB.

**Comment by djacquel** [comment]
Let's do without tags for now. Search might do a better work.

**Comment by captaincoffee** [comment]
Works for me.
